<div class="content-header">
    <div class="header-section">
        <h1>
            <?= $pageTitle ?><br>
        </h1>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="block">
        <form method="post" action="#">
            <div class="form-group">
                <label>Class Name</label>
                <input type="text" name="inputclsname" placeholder="Class Name" class="form-control" required>
            </div>
            <div class="form-group">
                <label>Class Details</label>
                <textarea type="text" name="inputclsdeta" placeholder="Class Details" class="form-control"></textarea>
            </div>
            <input type="submit" value="Save" class="btn btn-info">
        </form>
        </div>
    </div>
</div>