<div class="content-header">
    <div class="header-section">
        <h1>
            <?= $pageTitle ?><br>
        </h1>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="block">
        <form action="#" method="post" name="creaexmppr">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <div class='pull-right'>Fields marked <span class="text-danger">*</span> are mandatory <button id="saveprofile" class="btn btn-success btn-xs">Save Changes</button></div>
                    <h3 class="panel-title"><?= $pageTitle ?></h3>
                </div>
                <div class="panel-body">
                    <div class="row">
                    <div class="col-md-12">
                        <div class="col-md-12">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="inputexcls">Select Class</label>
                                    <select class="form-control" name="inputexcls" required>
                                    <?php 
                                      foreach($excls as $key => $value){
                                          echo "<option value='".$value->getId()."'>".$value->getName()."</option>";
                                      }
                                    ?>
                                    </select>
                                  </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                <label for="inputexsubj">Select Subject</label>
                                <select class="form-control" name="inputexsubj" required>
                                    <?php 
                                      foreach($exsub as $key => $subj){
                                          echo "<option value='".$subj->getEid()."'>".$subj->getName()."</option>";
                                      }
                                    ?>
                                </select>
                              </div>
                            </div>
                            <div class="form-group">
                              <label for="inputexquest">Question</label>
                              <textarea type="text" class="form-control" name="inputexquest"  rows="10" required></textarea>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                              <label for="inputexopt1">Option 1</label>
                              <textarea type="text" class="form-control" name="inputexopt1"  rows="2" required></textarea>
                            </div>
                            <div class="form-group">
                              <label for="inputexopt2">Option 2</label>
                              <textarea type="text" class="form-control" name="inputexopt2"  rows="2" required></textarea>
                            </div>
                            <div class="form-group">
                              <label for="inputexopt3">Option 3</label>
                              <textarea type="text" class="form-control" name="inputexopt3"  rows="2"></textarea>
                            </div>
                            <div class="form-group">
                              <label for="inputexopt4">Option 4</label>
                              <textarea type="text" class="form-control" name="inputexopt4"  rows="2"></textarea>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                              <label for="inputexquest">Correct Answer</label>
                              <input type="radio" name="inputexans" value="1"> 1
                              <input type="radio" name="inputexans" value="2"> 2
                              <input type="radio" name="inputexans" value="3"> 3
                              <input type="radio" name="inputexans" value="4"> 4
                            </div>
                        </div>
                    </div>
                    </div>
                </div>
                <div class="panel-footer text-center">
                    <button id="saveprofile" class="btn btn-success">Save Changes</button>
                </div>
            </div>
        </form>
        </div>
    </div>
</div>