<div class="content-header">
    <div class="header-section">
        <h1>
            <?= $pageTitle ?><br>
        </h1>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="block">

        <p class="text-center"><a href="/admin/exam/create-question" class="btn btn-info btn-xs">Add Question</a></p>
        <table class="table table-striped table-responsive" id="listqstn">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Question</th>
                    <th>Options</th>
                    <th>Answer</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
        <?php 
            foreach ($allqstn AS $key => $qstn){ ?>
                <tr>
                    <td><?= $qstn->getId() ?></td>
                    <td><?= $qstn->getExquest() ?></td>
                    <td>
                        <?= $qstn->getExchoice1() ?><br>
                        <?= $qstn->getExchoice2() ?><br>
                        <?= $qstn->getExchoice3() ?><br>
                        <?= $qstn->getExchoice4() ?><br>
                    </td>
                    <td>
                        <?= $qstn->getExcrchoice() ?>
                    </td>
                    <td><a href="<?php echo $this->basePath(); ?>/admin/exam/edit-question?qstid=<?= $qstn->getId() ?>">Edit</a></td>
                </tr>
        <?php } ?>
            </tbody>
        </table>
        </div>
    </div>
</div>
<script type="text/javascript">
$(function(){
    $("#listqstn").DataTable({
        "lengthMenu": [ [10, 25, 50, 100, -1], [10, 25, 50, 100, "All"] ],
    });
});
</script>