<div class="content-header">
    <div class="header-section">
        <h1>
            <?= $pageTitle ?><br>
        </h1>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="block">
        <p class="text-center"><a href="/admin/exam/add-subject" class="btn btn-info btn-xs">Add Subject</a></p>
        <table class="table table-striped table-responsive">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Name</th>
                    <th>Details</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
        <?php 
            foreach ($allsubj AS $key => $subj){ ?>
                <tr>
                    <td><?= $subj->getEid() ?></td>
                    <td><?= $subj->getName() ?></td>
                    <td><?= $subj->getDetails() ?></td>
                    <td><a href="/admin/exam/edit-subject?subjid=<?= $subj->getEid(); ?>" data-toggle="tooltip" title="Edit"><i class="fa fa-pencil-square fa-2x"></i></a></td>
                    <td><a href="/admin/exam/delete-subject?subjid=<?= $subj->getEid(); ?>" data-toggle="tooltip" title="Delete" class="text-danger" onclick="return confirm('Are you sure you want to delete this record?');"><i class="fa fa-trash-o fa-2x"></i></a></td>
                </tr>
        <?php } ?>
            </tbody>
        </table>
        </div>
    </div>
</div>