<div class="content-header">
    <div class="header-section">
        <h1>
            <?= $pageTitle ?><br>
        </h1>
    </div>
</div>
<div class="block">
    <?php if(!empty($message)){ ?>
        <div class="alert alert-info text-center"><h4><?= $message ?></h4></div>
        <p>&nbsp;</p>
    <?php } ?>
    <form method="post" action="#" class="form">
        <div class="form-group">
            <input class="form-control" type="text" name="stdid" placeholder="Enter User ID" required="required"/>
        </div>
        <div class="form-group">
            <input class="btn btn-lg btn-primary" type="submit" value="Reset Exam Now" name="submit" onclick="return confirm('Are you sure? Cannot revert back once Reset!!')"/>
        </div>
    </form>
</div>
