<div class="content-header">
    <div class="header-section">
        <h1>
            <?= $pageTitle ?><br>
        </h1>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="row">
            <div class="col-md-6">
                <div class="block">
                    <div class="block-title text-center">
                        <h2>Exam Status Graph</h2>
                    </div>
                    <div class="block-body text-center">
                        <div id="convstats" style="height: 250px;"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <table class="table table-bordered table-condensed table-striped">
            <thead>
                <tr>
                    <th>
                        Id
                    </th>
                    <th>
                        Username
                    </th>
                    <th>
                        Phone
                    </th>
                    <th>
                        Class
                    </th>
                    <th>
                        City
                    </th>
                    <th>
                        School
                    </th>
                    <th>
                        Score
                    </th>
                </tr>
            </thead>
            <tbody>
                <?php 
                    foreach ($exSubmitStat AS $key => $stats){
                ?>
                <tr>
                    <td><?= $stats->userId->getId() ?></td>
                    <td><?= $stats->userId->getUsername() ?></td>
                    <td><?= $stats->userId->getphonenum() ?></td>
                    <td></td>
                    <td></td>
                    <td><?= $stats->userId->student->schoolColg ?></td>
                    
                    <td><?= $stats->totalScore * 2 ?></td>
                </tr>
                <?php } ?>
            </tbody>
        </table>
    </div>
</div>

<script type="text/javascript">
Morris.Donut({
  element: 'convstats',
  colors : ["#1DE9B6", "#D50000"],
  data: [
    {label: "Total Completed", value: <?= $countExComp; ?>},
    {label: "Total Started", value: <?= $countExStart; ?>},
  ]
});

</script>