<div class="content-header">
    <div class="header-section">
        <h1>
            Current Events<br><small></small>
        </h1>
    </div>
</div>

<div class="row">
    <div class="col-md-6">
        <!-- Advanced Animated Gallery Widget -->
        <div class="widget">
            <div class="widget-advanced widget-advanced-alt">
                <!-- Widget Header -->
                <div class="widget-header text-left">
                    <!-- For best results use an image with at least 150 pixels in height (with the width relative to how big your widget will be!) - Here I'm using a 1200x150 pixels image -->
                    <img src="/img/event_header01.jpg" alt="background" class="widget-background animation-pulseSlow">
                    <h3 class="widget-content widget-content-image widget-content-light clearfix">
                          <a href="javascript:void(0)" class="themed-color-default">Bright Life Scholarship <strong> March 2016</strong></a><br>
                        <small>Presented by <a href="http://blfngoindia.com" target="_blank">Bright Life Foundation</a></small>
                    </h3>
                </div>
                <!-- END Widget Header -->

                <!-- Widget Main -->
                <div class="widget-main">
                    <p>One of the Competition is going to held for the school students is <strong>Bright Life Scholarship</strong> March 2015 which is presented by Bright Life Foundation. It is one of the biggest Competition for the school goers to Win a grand cash Scholarship worth Rupees One Lac (1,00,000/-) and other exciting prizes.<br>
                                                                <br>for more detail <a href="http://online-exam.in/" target="_blank"><button type="button" class="btn btn-primary">click here</button></a></p>
                                                        </div>
                <!-- END Widget Main -->
            </div>
        </div>
        <!-- END Advanced Animated Gallery Widget -->
    </div>
</div>