<div class="content-header">
    <div class="header-section">
        <h1>
            Upcoming Events<br><small></small>
        </h1>
    </div>
</div>
<div class="row">
    <div class="col-md-6">
        <div class="widget">
            <div class="widget-advanced widget-advanced-alt">
                <div class="widget-header text-left">
                    <img src="/img/event_header01.jpg" alt="background" class="widget-background animation-pulseSlow">
                    <h3 class="widget-content widget-content-image widget-content-light clearfix">
                          <a href="javascript:void(0)" class="themed-color-default">Bright Life Scholarship <strong> September 2015</strong></a><br>
                        <small>Presented by <a href="http://blfngoindia.com" target="_blank">Bright Life Foundation</a></small>
                    </h3>
                </div>

                <div class="widget-main">
                    <p>One of the Competition is going to held for the school students is <strong>Bright Life Scholarship</strong> September 2016 which is presented by Bright Life Foundation. It is one of the biggest Competition for the school goers to Win a grand cash Scholarship worth Rupees One Lac (1,00,000/-) and other exciting prizes.<br>
                            <br>for more detail <a href="http://online-exam.in/" target="_blank"><button type="button" class="btn btn-primary">click here</button></a></p>
                </div>
            </div>
        </div>
    </div>
</div>