<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Online Exam')->setAutoEscape(false) ?>
        <link rel="apple-touch-icon" sizes="57x57" href="/img/favicon/apple-icon-57x57.png">
        <link rel="apple-touch-icon" sizes="60x60" href="/img/favicon/apple-icon-60x60.png">
        <link rel="apple-touch-icon" sizes="72x72" href="/img/favicon/apple-icon-72x72.png">
        <link rel="apple-touch-icon" sizes="76x76" href="/img/favicon/apple-icon-76x76.png">
        <link rel="apple-touch-icon" sizes="114x114" href="/img/favicon/apple-icon-114x114.png">
        <link rel="apple-touch-icon" sizes="120x120" href="/img/favicon/apple-icon-120x120.png">
        <link rel="apple-touch-icon" sizes="144x144" href="/img/favicon/apple-icon-144x144.png">
        <link rel="apple-touch-icon" sizes="152x152" href="/img/favicon/apple-icon-152x152.png">
        <link rel="apple-touch-icon" sizes="180x180" href="/img/favicon/apple-icon-180x180.png">
        <link rel="icon" type="image/png" sizes="192x192"  href="/img/favicon/android-icon-192x192.png">
        <link rel="icon" type="image/png" sizes="32x32" href="/img/favicon/favicon-32x32.png">
        <link rel="icon" type="image/png" sizes="96x96" href="/img/favicon/favicon-96x96.png">
        <link rel="icon" type="image/png" sizes="16x16" href="/img/favicon/favicon-16x16.png">
        <link rel="manifest" href="/img/favicon/manifest.json">
        <meta name="msapplication-TileColor" content="#ffffff">
        <meta name="msapplication-TileImage" content="/img/faviconms-icon-144x144.png">
        <meta name="theme-color" content="#ffffff">
        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
            ->prependStylesheet($this->basePath('css/app_fix.css'))
            ->prependStylesheet($this->basePath('css/themes.css'))
            ->prependStylesheet($this->basePath('css/main.css'))
            ->prependStylesheet($this->basePath('css/morris.css'))
            ->prependStylesheet($this->basePath('css/datatables.min.css'))
            ->prependStylesheet($this->basePath('css/plugins.css'))
            ->prependStylesheet($this->basePath('plugins/font-awesome/css/font-awesome.min.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css')) ?>

        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/app.js'))
            ->prependFile($this->basePath('js/plugins.js'))
            ->prependFile($this->basePath('js/additional-methods.js'))
            ->prependFile($this->basePath('js/jquery.validate.min.js'))
            ->prependFile($this->basePath('js/angular.min.js'))
            ->prependFile($this->basePath('js/morris.min.js'))
            ->prependFile($this->basePath('js/datatables.min.js'))
            ->prependFile($this->basePath('js/raphael-min.js'))
            //->prependFile($this->basePath('js/jquery.simple.timer.js'))
            ->prependFile($this->basePath('js/jquery.plugin.min.js'))
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery.min.js'))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>
    </head>
    <body>
    <?php
        $roletype = $this->zfcUserIdentity()->getRoles();
        $role = $roletype[0]->getroleId();
    ?>
    <div id="page-wrapper">
        <div id="page-container" class="sidebar-partial sidebar-visible-lg sidebar-no-animations">
            <?php if($role == 'student') {
                echo $this->render('layout/side-menu-student');
            } elseif($role == 'admin') {
                echo $this->render('layout/side-menu-admin');
            } elseif($role == 'manager') {
                echo $this->render('layout/side-menu-manage');
            } else {

            }
            ?>
            <div id="main-container">
            <?php if($role == 'student') {
                echo $this->render('layout/top-menu-student');
            } elseif($role == 'admin') {
                echo $this->render('layout/top-menu-admin');
            } elseif($role == 'manager') {
                echo $this->render('layout/top-menu-manage');
            } else {

            }
            ?>
