            <footer class="clearfix">
                <div class="pull-right">
                    Developed by <a href="http://thetech24.com/" target="_blank">the TECH 24</a>
                </div>
                <div class="pull-left">
                    <span id="year-copy"></span> &copy; <a href="http://blfngoindia.org/" target="_blank">Bright Life Foundation</a>
                </div>
            </footer>
        <?php echo $this->inlineScript() ?>
        </div>
        </div>
        </div>
    </body>
</html>