            <footer class="clearfix">
                <div class="pull-right">
                    Developed by <a href="http://www.askforweb.com/" target="_blank">Askforweb</a>
                </div>
                <div class="pull-left">
                    <span id="year-copy"></span> &copy; <a href="http://www.askforweb.com/" target="_blank">Askforweb</a>
                </div>
            </footer>
        <?php echo $this->inlineScript() ?>
        </div>
        </div>
        </div>
    </body>
</html>
