<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Online Exam Software brought to you the TECH 24</title>
        <meta name="viewport" content="width=device-width, initial-scale=0.9">
        <link href="mainsite/css/bootstrap.css" rel="stylesheet" type="text/css" media="all" />
        <link href="mainsite/css/themify-icons.css" rel="stylesheet" type="text/css" media="all" />
        <link href="mainsite/css/flexslider.css" rel="stylesheet" type="text/css" media="all" />
        <link href="mainsite/css/lightbox.min.css" rel="stylesheet" type="text/css" media="all" />
        <link href="mainsite/css/ytplayer.css" rel="stylesheet" type="text/css" media="all" />
        <link href="mainsite/css/theme-purple.css" rel="stylesheet" type="text/css" media="all" />
        <link href="mainsite/css/custom.css" rel="stylesheet" type="text/css" media="all" />
        <link href='http://fonts.googleapis.com/css?family=Lato:300,400%7CRaleway:100,400,300,500,600,700%7COpen+Sans:400,500,600' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">

    </head>
    <body>
        <div class="nav-container">
            <a id="top"></a>
            <nav class="absolute transparent">
                <div class="nav-bar">
                    <div class="module left">
                        <a href="index.html" style="margin-top: 5px">
                        <h3 style="color:#fff" class="large logo logo-light">Online Exam</h3>
                        <h3 style="color:#000" class="large logo logo-dark">Online Exam</h3>
                        </a>
                    </div>
                    <div class="module widget-handle mobile-toggle right visible-sm visible-xs">
                        <i class="ti-menu"></i>
                    </div>
                    <div class="module-group right">
                        <div class="module left">
                            <ul class="menu">
                                <li>
                                    <a href="#top">
                                        Home
                                    </a>
                                 </li>
<li>
                                    <a href="#about">
                                        About us
                                    </a>
                                 </li>
<li>
                                    <a href="#tour">
                                        Tour
                                    </a>
                                 </li>
<li>
                                    <a href="#features">
                                        Features
                                    </a>
                                 </li>
<li>
                                    <a href="#pricing">
                                        Pricing
                                    </a>
                                 </li>
<li>
                                    <a href="#achievement">
                                        achievement
                                    </a>
                                 </li>
<li>
                                    <a href="#demo">
                                        Demo
                                    </a>
                                 </li>
<li>
                                    <a href="#contact">
                                        Contact us
                                    </a>
                                 </li>
                                
                            </ul>
                        </div>
                        <!--end of menu module-->
                        
                        <div class="module widget-handle cart-widget-handle left">
                            <div class="cart">
                                <i class="fa fa-sign-in"></i>
                            </div>
                            <div class="function">
                                <div class="widget">
                                    <h6 class="title">Shopping Cart</h6>
                                    <hr>
                                    <ul class="cart-overview">                                        
                                        <li>
                                            <div class="cart-controls">
                                    <h4 class="text-center">Bright Life Scholarship</h4>
                                        <a class="btn btn-sm btn-filled" href="http://blf.online-exam.in/user/login" target="_blank">Login</a>
                                        <a class="btn btn-sm btn-filled pull-right" href="http://blf.online-exam.in/user/register" target="_blank">Register</a>
                                    </div>
                                        </li>
                                        <hr style="color: #000">
                                        <li>
                                            <div class="cart-controls">
                                    <h4 class="text-center">Merchant Navy</h4>
                                        <a class="btn btn-sm btn-filled" href="#">Login</a>
                                        <a class="btn btn-sm btn-filled pull-right" href="#">Register</a>
                                    </div>
                                        </li>
                                    </ul>
                                </div>
                                <!--end of widget-->
                            </div>
                        </div>
                        <div class="module widget-handle language left">
                            <ul class="menu">
                                
                            </ul>
                        </div>
                    </div>
                    <!--end of module group-->
                </div>
            </nav>
        </div>
        <div class="main-container">
            <section class="bg-primary pb0">
                <div class="container pt80">
                    <div class="row mb24 mb-xs-0">
                        <div class="col-sm-10 col-sm-offset-1 text-center">
                            <h1 class="large">Online Exam Software</h1>
                            <p class="lead">
                                We provide more scalable, more reliable & low cost application platform
                            </p>
                        </div>
                    </div>
                    <!--end of row-->
                    <div class="row mb80 mb-xs-24">
                        <div class="col-sm-6 col-sm-offset-3">
                            <form class="form-newsletter halves" data-success="Thanks for your registration, we will be in touch shortly." data-error="Please fill all fields correctly.">
                                <input type="text" name="email" class="transparent validate-email validate-required  signup-email-field" placeholder="Phone No." style="color:#fff" />
                                <button type="submit" class="btn-white">Request for Demo</button>
                            </form>
                        </div>
                    </div>
                    <!--end of row-->
                    <div class="row">
                        <img alt="Online exam" src="img/online-app1.png" class="img-responsive" />
                    </div>
                    <!--end of row-->
                </div>
                <!--end of container-->
            </section>
            <section class="bg-dark pt-xs-40 pb-xs-40" id="about">
                <div class="container">
                    <div class="row">
                    <div class="col-md-2"></div>
                    <div class="col-md-8 text-center">
                     <h2 class="large">About us</h2>
                    <p>Online Exam software product developed by <strong>TECH 24</strong> which is secured with Capture Webcam and desktop. While student apearing for a exam, it is secured as while giving test student can not go outside window.</p><br></br>
                    </div>
                    <div class="col-md-2"></div>
                        <div class="col-sm-6 col-md-4 col-md-offset-2">
                            <div class="feature feature-3 mb-xs-24">
                                <div class="left">
                                    <i class="ti-signal icon-sm"></i>
                                </div>
                                <div class="right">
                                    <h4 class="mb16">Multiple Candidate</h4>
                                    <p>
                                        Online Exam is Designated for multiple candidates and each can be provided multiple test to perform their and then performance graph can also be generated.
                                    </p>
                                </div>
                            </div>
                            <!--end of feature-->
                        </div>
                        <div class="col-sm-6 col-md-4">
                            <div class="feature feature-3 mb-xs-24">
                                <div class="left">
                                    <i class="ti-ruler-alt icon-sm"></i>
                                </div>
                                <div class="right">
                                    <h4 class="mb16">Secure Exam</h4>
                                    <p>
                                        Online exam is secured with Capture Webcam and desktop. While student apearing for a exam, it is secured as while giving test student can not go outside window.
                                    </p>
                                </div>
                            </div>
                            <!--end of feature-->
                        </div>
                        <div class="col-sm-6 col-md-4 col-md-offset-2">
                            <div class="feature-3 mb-xs-24">
                                <div class="left">
                                    <i class="ti-layers icon-sm"></i>
                                </div>
                                <div class="right">
                                    <h4 class="mb16">Candidate Management</h4>
                                    <p>
                                        Candidate are managed in a proper way and email and sms is generated on registration and they can be mailed anytime needed.
                                    </p>
                                </div>
                            </div>
                            <!--end of feature-->
                        </div>
                        <div class="col-sm-6 col-md-4">
                            <div class="feature-3">
                                <div class="left">
                                    <i class="ti-heart icon-sm"></i>
                                </div>
                                <div class="right">
                                    <h4 class="mb16">Performance Evaluation</h4>
                                    <p>
                                        A well facilitated chart are generated for candidates so they can cross check where they are potential or where they are weak.
                                    </p>
                                </div>
                            </div>
                            <!--end of feature-->
                        </div>
                    </div>
                    <!--end of row-->
                </div>
                <!--end of container-->
            </section>
            <section class="bg-primary" id="tour">
                <div class="container">
                    <div class="row mb64 mb-xs-24">
                        <div class="col-md-8 col-md-offset-2 col-sm-10 col-sm-offset-1 text-center">
                            <h3 class="mb40 mb-xs-24">A Generic Online Exam System for All</h3>
                            <p class="lead">
                                Online Exam is Designated for multiple candidates and each can be provided multiple test
                            </p>
                        </div>
                    </div>
                    <!--end of row-->
                    <div class="row mb48 mb-xs-24">
                        <div class="col-sm-8 col-sm-offset-2">
                            <div class="local-video-container mb40">                                
                                <img src="img/online-app-l.png" class="img-responsive">
                            </div>
                            <!--end of local inline video-->
                        </div>
                    </div>
                </div>
                <!--end of container-->
            </section>
            <section class="image-edge pt120 pb120 pt-xs-40 pb-xs-40" id="features">
                <div class="col-md-6 col-sm-4 p0 col-md-push-6 col-sm-push-8">
                    <img alt="Online Exam" class="cast-shadow mb-xs-24" src="img/online-app-admin.png" />
                </div>
                <div class="container">
                    <div class="col-md-5 col-md-pull-0 col-sm-7 col-sm-pull-4 v-align-transform">
                        <h3 class="mb40 mb-xs-16">Conduct Online Exams, Assessment Process in Paperless way</h3>
                        <div class="feature boxed">
                            <ul>
                                <li>1. Secured platform</li>
                                 <li>2. Create & Deliver Exams Easily</li>
                                  <li>3. Integrated email and SMS</li>
                                  <li>4. Easy to use for everyone</li>                                  
                                    <li>5. Create exam quickly by choosing option of random questions</li>
                                     <li>6. Instant scorecard after submitting the online test</li>
                                    <li>7. User friendly when it comes to creating and conducting</li>
                            </ul>
                        </div>
                    </div>
                </div>
                <!--end of container-->
            </section>
    
            <section id="pricing">
                <div class="container">
                    <div class="row">
                        <div class="col-sm-12 text-center">
                            <h1 class="thin mb80 mb-xs-24">Plans & Pricing</h1>
                        </div>
                    </div>
                    <!--end of row-->
                    <div class="row">
                        <div class="col-md-4 col-sm-6 col-md-offset-2">
                            <div class="pricing-table pt-1 text-center">
                                <H5 class="uppercase">Starter Package</H5>
                                <span class="price">$ 333</span>
                                <p class="lead">5000 tests per year</p>
                                <a class="btn btn-filled btn-lg" href="#">Get Started</a>
                                <p>
                                    30 Day Free Trial
                                    <br /> All features included
                                </p>
                            </div>
                            <!--end of pricing table-->
                        </div>
                        <div class="col-md-4 col-sm-6">
                            <div class="pricing-table pt-1 text-center emphasis">
                                <H5 class="uppercase">Enterprise Package</H5>
                                <span class="price">$ 550</span>
                                <p class="lead">12000 tests per year</p>
                                <a class="btn btn-white btn-lg" href="#">Get Started</a>
                                <p>
                                    30 Day Free Trial
                                    <br /> All features included
                                </p>
                            </div>
                            <!--end of pricing table-->
                        </div>
                    </div>
                    <!--end of row-->
                </div>
                <!--end of container-->
                <div class="embelish-icons">
                    <i class="ti-marker"></i>
                    <i class="ti-layout"></i>
                    <i class="ti-ruler-alt-2"></i>
                    <i class="ti-eye"></i>
                    <i class="ti-signal"></i>
                    <i class="ti-pulse"></i>
                    <i class="ti-marker"></i>
                    <i class="ti-layout"></i>
                    <i class="ti-ruler-alt-2"></i>
                    <i class="ti-eye"></i>
                    <i class="ti-signal"></i>
                    <i class="ti-pulse"></i>
                </div>
            </section>
            <section class="image-bg overlay parallax">
                <div class="background-image-holder">
                    <img alt="Online exam" class="background-image" src="img/online-app2.jpg" />
                </div>
                <div class="container">
                    
                    <!--end of row-->
                    <div class="row mb16 mb-xs-0">
                        <div class="col-sm-12 text-center">
                            <h3>Clients Feedback</h3>
                        </div>
                    </div>
                    <!--end of row-->
                    <div class="row">
                        <div class="col-md-8 col-md-offset-2 col-sm-10 col-sm-offset-1">
                            <div class="text-slider slider-arrow-controls text-center relative">
                                <ul class="slides">
                                    <li>
                                        <p class="lead">The Online Exam saved us time and money. It also increased transparency and security in our exam process.</p>
                                        <div class="quote-author">
                                            <h6 class="uppercase mb0">Vikash Aggarwal</h6>
                                            <span>President, Bright Life Foundation</span>
                                        </div>
                                    </li>
                                    <li>
                                        <p class="lead">Our students can now get accurate and quick feedback. The system is available to users 24x7. We are very satisfied with the Online Exam.</p>
                                        <div class="quote-author">
                                            <h6 class="uppercase mb0">Arjun Singh</h6>
                                            <span>New Delhi, India</span>
                                        </div>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <!--end of row-->
                </div>
                <!--end of container-->
            </section>
            <section class="bg-secondary" id="achievement">
                <div class="container">
                    <div class="row mb40 mb-xs-0">
                        <div class="col-sm-12 text-center">
                            <h4 class="uppercase">Numbers Speak Aloud</h4>
                        </div>
                    </div>
                    <!--end of row-->
                    <div class="row">
                        <div class="col-sm-6 col-md-5 text-right text-center-xs">
                            <h1 class="large mb8">12778+</h1>
                            <h6 class="uppercase">student given exam</h6>
                        </div>
                        <div class="col-md-2 text-center hidden-sm hidden-xs">
                            <i class="ti-infinite icon icon-lg color-primary mt8 mt-xs-0"></i>
                        </div>
                        <div class="col-sm-6 col-md-5 text-center-xs">
                            <h1 class="large mb8">2554+</h1>
                            <h6 class="uppercase">Questions Created</h6>
                        </div>
                    </div>
                    <!--end of row-->
                </div>
                <!--end of container-->
            </section>
            <section class="bg-primary" id="demo">
                <div class="container">
                    <div class="row mb64 mb-xs-24">
                        <div class="col-sm-12 text-center">
                            <h3>Request a Demo</h3>
                        </div>
                    </div>
                    <!--end of row-->
                    <div class="row mb40 mb-xs-24">
                        <div class="col-sm-6 col-sm-offset-3">
                            <form class="form-newsletter halves" data-success="Thanks for your registration, we will be in touch shortly." data-error="Please fill all fields correctly.">
                                <input type="text" name="email" class="transparent validate-email validate-required  signup-email-field" placeholder="Phone No." style="color:#fff" />
                                <button type="submit" class="btn-white">Submit</button>
                            </form>
                        </div>
                    </div>
                </div>
                <!--end of container-->
            </section>
            <section class="bg-secondary" id="contact">
                <div class="container">
                    <div class="row mb40 mb-xs-0">
                        <div class="col-sm-12 text-center">
                            <h4 class="uppercase">Contact us</h4>
                        </div>
                    </div>
                    <!--end of row-->
                    <div class="row">
                        <div class="col-sm-6 col-md-5 text-right text-center-xs">
                            <h4 class="uppercase">Email:<br> thetech244@gmail.com</h4>
                        </div>
                        <div class="col-md-2 text-center hidden-sm hidden-xs">
                            <i class="ti-infinite icon icon-lg color-primary mt8 mt-xs-0"></i>
                        </div>
                        <div class="col-sm-6 col-md-5 text-center-xs">
                            <h4 class="uppercase">Phone:<br> +91 8929808808, +91 8929811811</h4>
                        </div>
                    </div>
                    <!--end of row-->

                </div>
                <!--end of container-->
                <p>Visitor<img src="http://hitwebcounter.com/counter/counter.php?page=6226172&amp;style=0006&amp;nbdigits=6&amp;type=page&amp;initCount=1000" title="Online Exam" border="0"></p> 
            </section>
            <footer class="footer-1 bg-dark">
                <div class="container">
                   
                    <!--end of row-->
                    <div class="row">
                        <div class="col-sm-6">
                            <span class="sub">&copy; 2016 the TECH 24. All rights reserved.</span>
                        </div>
                        <div class="col-sm-6 text-right">
                            <ul class="list-inline social-list">
                                <li>
                                    <a href="#">
                                        <i class="ti-twitter-alt"></i>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <i class="ti-facebook"></i>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <i class="ti-dribbble"></i>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <i class="ti-vimeo-alt"></i>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
                <!--end of container-->
                <a class="btn btn-sm fade-half back-to-top inner-link" href="#top">Top</a>

            </footer>
        </div>
        <script src="mainsite/js/jquery.min.js"></script>
        <script src="mainsite/js/bootstrap.min.js"></script>
        <script src="mainsite/js/flickr.js"></script>
        <script src="mainsite/js/flexslider.min.js"></script>
        <script src="mainsite/js/lightbox.min.js"></script>
        <script src="mainsite/js/masonry.min.js"></script>
        <script src="mainsite/js/twitterfetcher.min.js"></script>
        <script src="mainsite/js/spectragram.min.js"></script>
        <script src="mainsite/js/ytplayer.min.js"></script>
        <script src="mainsite/js/countdown.min.js"></script>
        <script src="mainsite/js/smooth-scroll.min.js"></script>
        <script src="mainsite/js/parallax.js"></script>
        <script src="mainsite/js/scripts.js"></script>
    </body>
</html>
