<div class="navbar-default sidebar" role="navigation">
<div class="sidebar-nav navbar-collapse">
<div class="panel-group" id="accordion">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h4 class="panel-title">
                <a href="/admin/admin/dashboard"><span class="glyphicon glyphicon-folder-close">
                </span>Dashboard</a>
            </h4>
        </div>
    </div>
    <!--<div class="panel panel-default">
        <div class="panel-heading">
            <h4 class="panel-title">
                <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne"><span class="glyphicon glyphicon-folder-close">
                </span>Student</a>
            </h4>
        </div>
        <div id="collapseOne" class="panel-collapse collapse in">
            <div class="panel-body">
                <table class="table">
                    <tr>
                        <td>
                            <span class="glyphicon glyphicon-pencil text-primary"></span><a href="#">View Student</a>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <span class="glyphicon glyphicon-flash text-success"></span><a href="#">Edit Student</a>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <span class="glyphicon glyphicon-file text-info"></span><a href="#">Newsletters</a>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <span class="glyphicon glyphicon-comment text-success"></span><a href="#">Comments</a>
                            <span class="badge">42</span>
                        </td>
                    </tr>
                </table>
            </div>
        </div>
    </div>-->
    <div class="panel panel-default">
        <div class="panel-heading">
            <h4 class="panel-title">
                <a data-toggle="collapse" data-parent="#accordion" href="#collapseTwo"><span class="glyphicon glyphicon-th">
                </span>Exam</a>
            </h4>
        </div>
        <div id="collapseTwo" class="panel-collapse collapse">
            <div class="panel-body">
                <table class="table">
                    <tr>
                        <td>
                            <a href="/admin/exam/create-question">Create Question</a>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <a href="/admin/exam/list-question">List Question</a>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <a href="/admin/exam/listsearch-question">Search Question</a>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <a href="/admin/exam/add-subject">Create Subject</a>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <a href="/admin/exam/list-subject">List Subject</a>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <a href="/admin/exam/add-class">Create Class</a>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <a href="/admin/exam/list-class">List Class</a>
                        </td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
    <div class="panel panel-default">
        <div class="panel-heading">
            <h4 class="panel-title">
                <a data-toggle="collapse" data-parent="#accordion" href="#collapseThree"><span class="glyphicon glyphicon-user">
                </span>User Accounts</a>
            </h4>
        </div>
        <div id="collapseThree" class="panel-collapse collapse">
            <div class="panel-body">
                <table class="table">
                    <tr>
                        <td>
                            <a href="/admin/student/list-students">List Students</a>
                        </td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
    <!--<div class="panel panel-default">
        <div class="panel-heading">
            <h4 class="panel-title">
                <a data-toggle="collapse" data-parent="#accordion" href="#collapseFour"><span class="glyphicon glyphicon-file">
                </span>Reports</a>
            </h4>
        </div>
        <div id="collapseFour" class="panel-collapse collapse">
            <div class="panel-body">
                <table class="table">
                    <tr>
                        <td>
                            <span class="glyphicon glyphicon-usd"></span><a href="#">Sales</a>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <span class="glyphicon glyphicon-user"></span><a href="#">Customers</a>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <span class="glyphicon glyphicon-tasks"></span><a href="#">Products</a>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <span class="glyphicon glyphicon-shopping-cart"></span><a href="#">Shopping Cart</a>
                        </td>
                    </tr>
                </table>
            </div>
        </div>
    </div>-->
</div>
</div>
</div>