<!-- Main Sidebar -->
<div id="sidebar">
    <!-- Wrapper for scrolling functionality -->
    <div id="sidebar-scroll">
        <!-- Sidebar Content -->
        <div class="sidebar-content">
            <!-- Brand -->
            <a href="/" class="sidebar-brand">
                <i class="fa fa-refresh fa-spin"></i>
                <span class="sidebar-nav-mini-hide">Online-Exam</span>
            </a>
            <!-- END Brand -->

            <!-- User Info -->
            <div class="sidebar-section clearfix sidebar-nav-mini-hide text-center">
                <img src="/img/logo.png">
            </div>
            <!-- END User Info -->

            <!-- Sidebar Navigation -->
            <ul class="sidebar-nav">
                <li>
                    <a href="/student/student/dashboard" class=" active"><i class="gi gi-stopwatch sidebar-nav-icon"></i> <span class="sidebar-nav-mini-hide">Dashboard</span></a>
                </li>
                <li>
                    <a href="javascript:void(0)" class="sidebar-nav-menu"><i class="fa fa-angle-left sidebar-nav-indicator sidebar-nav-mini-hide"></i><i class="fa fa-user sidebar-nav-icon"></i> <span class="sidebar-nav-mini-hide">Profile</span></a>
                    <ul>
                        <li>
                            <a href="/student/student/profile">View Profile</a>
                        </li>
                        <li>
                            <a href="/student/student/edit-profile">Edit Profile</a>
                        </li>
                    </ul>
                </li>
                <!--<li>
                    <a href="javascript:void(0)" class="sidebar-nav-menu"><i class="fa fa-angle-left sidebar-nav-indicator sidebar-nav-mini-hide"></i><i class="fa fa-calendar sidebar-nav-icon"></i> <span class="sidebar-nav-mini-hide">Events</span></a>
                    <ul>
                        <li>
                            <a href="/stevent/index">Current Events</a>
                        </li>
                        <li>
                            <a href="/stevent/upcoming-events">Upcoming Events</a>
                        </li>
                        <li>
                            <a href="/stevent/prev-events">Previous Events</a>
                        </li>
                    </ul>
                </li>-->
                <li>
                    <a href="/streferral/referral-dashboard"><i class="fa fa-calendar sidebar-nav-icon"></i> <span class="sidebar-nav-mini-hide">Refer Friends</span></a>
                </li>
                <li>
                    <a href="/about-us"><i class="fa fa-anchor sidebar-nav-icon"></i> <span class="sidebar-nav-mini-hide">About us</span></a>
                </li>
                <!--<li>
                    <a href="/faqs"><i class="fa fa-question-circle sidebar-nav-icon"></i> <span class="sidebar-nav-mini-hide">FAQs</span></a>
                </li>-->
                <li>
                    <a href="/support"><i class="fa fa-life-ring sidebar-nav-icon"></i> <span class="sidebar-nav-mini-hide">Support</span></a>
                </li>
                <li>
                    <a href="/terms"><i class="fa fa-file-text-o sidebar-nav-icon"></i> <span class="sidebar-nav-mini-hide">Terms and conditions</span></a>
                </li>

                <li>
                    <a href="/contact"><i class="fa fa-phone sidebar-nav-icon"></i> <span class="sidebar-nav-mini-hide">Contact us</span></a>
                </li>
            </ul>
            <!-- END Sidebar Navigation -->
        </div>
        <!-- END Sidebar Content -->
        <br><br>
        <div class="col-md-12">
                <div class="panel panel-danger">
                        <div class="panel-heading">
                                <i class="fa fa-bullhorn"></i> Notifications
                        </div>
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                                <div class="list-group text-center">
                                           Last Date of Registration is<br>
                                           <strong>31st March 2016</strong><br><br>
                                           For more info please visit<br>
                                           <strong><a href="http://www.blfngoindia.org/" target="_blank">www.blfngoindia.org</a></strong>

                                   <p></p>
                                </div>
                        </div>
                        <!-- /.panel-body -->
                </div>
        </div>
    </div>
    <!-- END Wrapper for scrolling functionality -->
</div>
<!-- END Main Sidebar -->