<div class="navbar-default sidebar" role="navigation">
    <div class="sidebar-nav navbar-collapse">
        <ul class="nav" id="side-menu">
            <li class="sidebar-search">
                <div class="input-group custom-search-form">
                    Manager Menu
                </div>
            </li>
            <li>
                <a href="/student/dashboard"><i class="fa fa-dashboard fa-fw"></i> Dashboard</a>
            </li>
            <li>
                <a href="/student/profile"><i class="fa fa-user fa-fw"></i> Profile</a>
            </li>
            <li>
                <a href="#"><i class="fa fa-trophy fa-fw"></i> Prize</a>
            </li>
            <li>
                <a href="#"><i class="fa fa-sitemap fa-fw"></i> About us</a>
            </li>
            <li>
                <a href="#"><i class="fa fa-table fa-fw"></i> Winners</a>
            </li>
            <li>
                <a href="#"><i class="fa fa-chain fa-fw"></i> Support</a>
            </li>
        </ul>
    </div><br><br>
    <div class="col-md-12">
        <div class="panel panel-red">
            <div class="panel-heading">
                <i class="fa fa-edit fa-fw"></i> Online Exam
            </div>
            <div class="panel-body">
                <div class="list-group">
                    Timer

                </div>
            </div>
        </div>
    </div>
</div>