<div id="sidebar">
    <div id="sidebar-scroll">
        <div class="sidebar-content">
            <a href="/" class="sidebar-brand">
                <i class="fa fa-refresh fa-spin"></i>
                <span class="sidebar-nav-mini-hide">Online-Exam</span>
            </a>
            <div class="sidebar-section clearfix sidebar-nav-mini-hide text-center">
                <img src="/img/logo.png">
            </div>
            <ul class="sidebar-nav">
                <li>
                    <a href="/student/student/dashboard" class=" active"><i class="gi gi-stopwatch sidebar-nav-icon"></i> <span class="sidebar-nav-mini-hide">Dashboard</span></a>
                </li>
                <li>
                    <a href="javascript:void(0)" class="sidebar-nav-menu"><i class="fa fa-angle-left sidebar-nav-indicator sidebar-nav-mini-hide"></i><i class="fa fa-user sidebar-nav-icon"></i> <span class="sidebar-nav-mini-hide">Manage Subjects</span></a>
                    <ul>
                        <li>
                            <a href="/admin/exam/add-subject">Add Subject</a>
                        </li>
                        <li>
                            <a href="/admin/exam/list-subject">List Subject</a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href="javascript:void(0)" class="sidebar-nav-menu"><i class="fa fa-angle-left sidebar-nav-indicator sidebar-nav-mini-hide"></i><i class="fa fa-user sidebar-nav-icon"></i> <span class="sidebar-nav-mini-hide">Manage Class</span></a>
                    <ul>
                        <li>
                            <a href="/admin/exam/add-class">Add Class</a>
                        </li>
                        <li>
                            <a href="/admin/exam/list-class">List Class</a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href="javascript:void(0)" class="sidebar-nav-menu"><i class="fa fa-angle-left sidebar-nav-indicator sidebar-nav-mini-hide"></i><i class="fa fa-calendar sidebar-nav-icon"></i> <span class="sidebar-nav-mini-hide">Manage Questions</span></a>
                    <ul>
                        <li>
                            <a href="/admin/exam/create-question">Create Question</a>
                        </li>
                        <li>
                            <a href="/admin/exam/list-question">List Question</a>
                        </li>
                        <li>
                            <a href="/admin/exam/listsearch-question">Search Question</a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href="javascript:void(0)" class="sidebar-nav-menu"><i class="fa fa-angle-left sidebar-nav-indicator sidebar-nav-mini-hide"></i><i class="fa fa-calendar sidebar-nav-icon"></i> <span class="sidebar-nav-mini-hide">User Management</span></a>
                    <ul>
                        <li>
                            <a href="/admin/student/list-students">List Students</a>
                            <a href="/admin/student/show-student-pass">List Students Passwords</a>
                            <a href="/admin/student/show-referrals">List Students Referrals</a>
                            <a href="/admin/student/show-referral-success">List Referrals Registered</a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href="javascript:void(0)" class="sidebar-nav-menu"><i class="fa fa-angle-left sidebar-nav-indicator sidebar-nav-mini-hide"></i><i class="fa fa-calendar sidebar-nav-icon"></i> <span class="sidebar-nav-mini-hide">Exam Management</span></a>
                    <ul>
                        <li>
                            <a href="/admin/exam/show-exam-status">Show Results</a>
                        </li>
                        <li>
                            <a href="/admin/exam/re-exam-student">Student Re-Exam</a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href="javascript:void(0)" class="sidebar-nav-menu"><i class="fa fa-angle-left sidebar-nav-indicator sidebar-nav-mini-hide"></i><i class="fa fa-bank sidebar-nav-icon"></i> <span class="sidebar-nav-mini-hide">Payment Status</span></a>
                    <ul>
                        <li>
                            <a href="/admin/student/list-students-payment">List Due Students</a>
                        </li>
                        <li>
                            <a href="/admin/student/list-students-paid">List Paid Students</a>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
        <br><br>
    </div>
</div>