<?php if ($this->zfcUserIdentity()): ?>
<header class="navbar navbar-default">
    <ul class="nav navbar-nav-custom">
        <li>
            <a href="javascript:void(0)" onclick="App.sidebar('toggle-sidebar');">
                <i class="fa fa-bars fa-fw"></i>
            </a>
        </li>
        <li class="dropdown">
            <h4>Bright Life Scholarship <?php echo date('Y'); ?></h4>
        </li>
    </ul>
    <ul class="nav navbar-nav-custom pull-right">
        <li class="dropdown">
            <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown">
                <?= $this->zfcUserIdentity()->getUsername() ?> <i class="fa fa-angle-down"></i>
            </a>
            <ul class="dropdown-menu dropdown-custom dropdown-menu-right">
                <li class="dropdown-header text-center">Account</li>
                <li>
                    <a href="/student/student/profile">
                        <i class="fa fa-user fa-fw pull-right"></i>
                        Profile
                    </a>
                    <a href="/student/student/dashboard">
                        <i class="fa fa-pencil-square-o fa-fw pull-right"></i>
                        <span class="badge pull-right"></span>
                        Dashboard
                    </a>
                    <a href="/user/change-password">
                        <i class="fa fa-pencil-square-o fa-fw pull-right"></i>
                        <span class="badge pull-right"></span>
                        Change Password
                    </a>
                </li>
                <li class="divider"></li>
                <li>
                    <a href="/faqs"><i class="fa fa-question-circle fa-fw pull-right"></i>
                        <span class="badge pull-right"></span>
                        FAQ
                    </a>

                    <a href="/support"><i class="fa fa-life-ring fa-fw pull-right"></i>
                        <span class="badge pull-right"></span>
                        Support
                    </a>
                </li>
            </ul>
        </li>
        <li>
            <a href="<?php echo $this->url('zfcuser/logout') ?>">
                Signout <i class="fa fa-power-off"></i>
            </a>
        </li>
    </ul>
</header>
<?php endif; ?>