<?php 
    if(!empty($msg)){
        echo '<br><div class="alert alert-warning">'.$msg.'</div>';
    } else {
        
    }
?>

<h3><?= $pageTitle ?></h3>
<?php if($pprattempt == 0){ ?>
<p class="text-center">
    <span class="alert alert-danger">Remaining Time : <?= $timetostop ?> <span id="countdown_exm"></span></span>
</p>
<br>
<form method="post" action="/stexam/submit-exam-paper" name="stdexamform" id="stdexamform">
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-info">
            <div class="panel-heading">
                <button class="btn btn-danger btn-xs pull-right" class="pprsubmit">Submit Paper</button>
                <h3 class="panel-title"><span class="label label-primary">Question : <span class="qnos">1</span> / <?= $totalqstns ?></span></h3>
            </div>
        </div>
        <?php foreach($myexamquestions as $key=> $questions){ ?>
        <div id="qstn<?= $key ?>" class="exqsppr" style="display:none;">
            <div class="panel-body">
                <table class="table table-bordered table-responsive">
                    <thead>
                    <tr>
                    <th colspan="2">
                        <h5>Question</h5>
                        <p><?= $questions['question'] ?></p>
                        <input type="hidden" name="qid_<?= $key ?>" value="<?= $questions['qsid'] ?>">
                    </th>
                    </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td><input type="radio" name="qans_<?= $key ?>" value="1"> <?= $questions['choice1'] ?></td>
                            <td><input type="radio" name="qans_<?= $key ?>" value="2"> <?= $questions['choice2'] ?></td>
                        </tr>
                        <tr>
                            <td><input type="radio" name="qans_<?= $key ?>" value="3"> <?= $questions['choice3'] ?></td>
                            <td><input type="radio" name="qans_<?= $key ?>" value="4"> <?= $questions['choice4'] ?></td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <div class="panel-footer">
                <?php if(count($myexamquestions)-1 != $key) { ?>
                <a class="btn btn-success pull-right qstnnxt" id="qstn_<?= $key ?>">Next</a>
                <?php } ?>
                <?php if(count($myexamquestions)-1 == $key) { ?>
                <button class="btn btn-danger pull-right" class="pprsubmit">Submit Paper</button>
                <?php } ?>
                <?php if($key != 0){ ?>
                <a class="btn btn-info pull-left qstnprev" id="pqstn_<?= $key ?>">Previous</a>
                <?php } ?>
                <div class="clearfix"></div>
            </div>
        </div>
        <?php } ?>
    </div>
    <input type="hidden" name="idpex" value="<?= $idpex ?>">
</div>
</form>    
<script>
$(function(){
    $('#qstn0').show();
    nxtqustn();
    prvqustn();
    var timeleft = <?= $timetostop ?> * 60 * 1000;
    //alert(timeleft);
    //$('#countdown_exmx').countdown({until: +600, padZeroes: true});
    //var count = timeleft;
    //var counter = setInterval(timer, 1000);
    setTimeout(autoSubmitform, timeleft);
});

function autoSubmitform(){
    $('#stdexamform').submit();
}

var count = <?= $timetostop ?>;
function timer() {
    count = count - 1;
    if (count == -1) {
        clearInterval(counter);
        return;
    }

    var seconds = count % 60;
    var minutes = Math.floor(count / 60);
    //var hours = Math.floor(minutes / 60);
    minutes %= 60;
    //hours %= 60;

    document.getElementById("countdown_exm").innerHTML = minutes + "min" + seconds + " seconds left"; // watch for spelling
}

function nxtqustn(){
    $('.qstnnxt').on('click', function(){
    var curq = $(this).attr('id');
    curq = curq.split('_');
    var nxtqid = curq[1];
    //alert(nxtqid);
    nxtqid++;
    //alert(nxtqid);
    var curqid = "#qstn"+curq[1];
    var nxtq = "#qstn"+nxtqid;
    $('.exqsppr').hide();
    var qnumb = $('.qnos').text();
    qnumb++;
    $('.qnos').text(qnumb);
    //$(curqid).removeClass('show');
    //$(curqid).addClass('hide');
    $(curqid).hide();
    //$(nxtq).removeClass('hide');
    $(nxtq).show();
    //$('.exqsppr').show();
    });
}
function prvqustn(){
    $('.qstnprev').on('click', function(){
    var curq = $(this).attr('id');
    curq = curq.split('_');
    var nxtqid = curq[1];
    nxtqid--;
    var curqid = "#qstn"+curq[1];
    var nxtq = "#qstn"+nxtqid;
    $('.exqsppr').hide();
    var qnumb = $('.qnos').text();
    qnumb--;
    $('.qnos').text(qnumb);
    $(curqid).hide();
    $(nxtq).show();
    });
}

setTimeout(function(){ 
    $(form).submit();
}, 3000);
</script>
<?php } else { ?>
<div class="alert alert-danger">Sorry, you have either completed the exam or the exam has expired.</div>
<?php } ?>
