<div class="content-header">
    <div class="header-section">
        <h1>
            <?= $pageTitle ?><br>
        </h1>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="block">
        <table class="table table-striped table-responsive" id="studunpaid">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Name</th>
                    <th>Username</th>
                    <th>Phone</th>
                    <th>Father's Name</th>
                    <th>Class</th>
                    <th>Pay Status</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
        <?php 
            foreach ($allstud AS $key => $stud){ ?>
                <tr>
                    <td><?= $stud->getId() ?></td>
                    <td><?= $stud->getFirstName()." ".$stud->getMiddleName()." ".$stud->getLastName() ?></td>
                    <td><?= $stud->getUserId()->getUsername() ?></td>
                    <td><?= $stud->getPhone(); ?></td>
                    <td><?= $stud->getFathername() ?></td>
                    <td><?= $stud->getClassGrade() ?></td>
                    <td><?php if(empty($stud->getPaystatus())) { echo "<label class='label label-danger'>Not Paid</label>"; } ?></td>
                    <td><span class="btn btn-sm btn-success makepay" id="<?= $stud->getId(); ?>" title="Mark Paid" style="cursor: pointer;"><i class="fa fa-check-circle"></i></span></td>
                </tr>
        <?php } ?>
            </tbody>
        </table>
        </div>
    </div>
</div>

<script>
$(function(){
   $(".makepay").on('click', function(){
       var stdid = $(this).attr('id');
       if(confirm("Are you sure to mark this Student Paid")){
           $.ajax({
            type: "POST",
            url: '/admin/student/student-mark-paid?stdid='+stdid,
            success: function(){
                alert("Payment status updated. Please wait while records are being fetched.");
                location.reload();
            },
          });
       };
   })
   $("#studunpaid").DataTable({
        "lengthMenu": [ [5, 10, 25, 50, 100, -1], [5, 10, 25, 50, 100, "All"] ],
    });
});


</script>