<div class="content-header">
    <div class="header-section">
        <h1>
            <strong><?= $pageTitle ?></strong> 
        </h1>
    </div>
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="block">
            <div class="block-title">
                <h2><i class="fa fa-file-o"></i><strong> <?= $pageTitle ?></strong><h2>
            </div>
            <div class="block-body">
            <p>
                eScholarship is an online scholarship exam brought to you by Bright Life Foundation (www.blfngoindia.org) which provides a platform for brilliant students. This software is promoted by highly qualified team and specialized in creating high impact online exam software which is highly efficient in terms of reliability and speed.
            The eScholarship Exam is based on a Multiple Choice Questions pattern which will help Student to be more precise & careful while attempting the questions. The questions and the marking scheme are designed in such a way that a student can develop decision making ability and the reasoning power.
            <br>
            eScholarship Exam is not only an important platform to identify and nurture the talented Student but also help in pinpointing areas of strength and weakness in every Student.
            The Bright Life Foundation has taken up an important task of searching young talents through eScholarship Exam.</p>
            <br>

            <h3>Examination Pattern</h3>
            <ul>
            <li>Exam will be objective type.</li>
            <li>Each question will be provided by 4 alternatives.</li>
            <li>Syllabus - English Grammar, Mathematics & Science, General Knowledge</li>
            <li>Total Questions – 50</li>
            <li>Total Marks – 100 (Each question will carry 2 mark.)</li>
            <li>Exam Duration – 30 min.</li>
            <li>Negative marking will not be applied for any wrong answer.</li>
            </ul>

            <h3>Registration</h3>
            <ul>
            <li>Registration Starts: 15 January 2016</li>
            <li>Last Date of application: 31st March 2016</li>
            <li>Exam Date: 9th, 10th and 11th April 2016</li>
            <li>Result Date: 17 April 2016</li>
            </ul>
            </div>
        </div>
    </div>
</div>