<div class="content-header">
    <div class="header-section">
        <h1>
            <strong><?= $pageTitle ?></strong> 
        </h1>
    </div>
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="block">
            <div class="block-title">
                <h2><i class="fa fa-file-o"></i><strong> <?= $pageTitle ?></strong><h2>
            </div>
            <h3 class="text-center">If you have any queries do get in touch with us. You can either e-mail us, call us or visit us.</h3>
            <br><br>
            <div class="row">
                <div class="col-md-6">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h4>Delhi Address</h4>
                        </div>
                        <div class="panel-body">
                            <p>H No. 685-B-2, Gosian Mohalla,<br> Najafgarh, <br>New Delhi-110043</p>
                            <p>Email: info@blfngoindia.org</p>
                            <p>Phone: 8929 806806</p>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h4>Haryana Address: (Mailing Address)</h4>
                        </div>
                        <div class="panel-body">
                            <p>Bright Life Foundation, <br>Kosli, Dist - Rewari, <br>Haryana-123302</p>
                            <p>Email: info@blfngoindia.org</p>
                            <p>Phone: 8929 807807</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>