<div class="content-header">
    <div class="header-section">
        <h1>
            <strong><?= $pageTitle ?></strong> 
        </h1>
    </div>
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="block" style="height:160px;">
            <div class="block-title">
                <h2><i class="fa fa-file-o"></i><strong> <?= $pageTitle ?></strong><h2>
            </div>
            <h3 class="text-center">coming soon</h3>
        </div>
    </div>
</div>