<div class="col-md-12 text-center">
    <h1>Cash Scholarship worth<h1>
    <h1 class="text-success">Rs. 1,00,000</h1>
    <h2 class="text-muted">&amp; Other Exciting Prizes</h2>
    </p>
</div>
<p>&nbsp;</p>
<div class="col-md-12 text-center">
    <h2 class="singleItemTitle cash">Full Marks Candidate 1 Laptop</h2>
    <table class="table table-bordered" style="font-size: 18px;">
        <tbody>
            <tr>
                <td>1st Position</td>
                <td>Rs. 21,000 <small>with Rs.500/- Month for 5 Years</small></td>
            </tr>
            <tr>
                <td>2nd Position</td>
                <td>Rs. 11,000 <small>with Rs.500/- Month for 5 Years</small></td>
            </tr>
            <tr>
                <td>3rd Position</td>
                <td>Rs. 5,100 <small>with Rs.500/- Month for 5 Years</small></td>
            </tr>
            <tr>
                <td>4th to 10th Position</td>
                <td>Rs. 2,100 <small>with Rs.500/- Month for 5 Years</small></td>
            </tr>
            <tr>
                <td>Above 60%</td>
                <td>Gift &amp; Scholarship Certificate</td>
            </tr>
        </tbody>
    </table>
</div>