<div class="content-header">
    <div class="header-section">
        <h1>
            <strong><?= $pageTitle ?></strong> 
        </h1>
    </div>
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="block">
            <div class="block-title">
                <h2><i class="fa fa-file-o"></i><strong> <?= $pageTitle ?></strong><h2>
            </div>
            <!--<h2 class="text-center">Please contact us at blfngoindia@gmail.com</h2>-->
            <?php if($successmsg !='') { ?>
            <div class="row">
                <div class="col-md-12 alert alert-success text-center">
                    <h5><?= $successmsg; ?></h5>
                </div>
            </div>
            <?php } ?>
          <div class="block-body">
            <div class="col-md-12">
            <form method="post" action="#">
                <div class="form-group">
                  <label for="inputname">Name</label>
                  <input type="text" class="form-control" name="inputname" id="inputname" value="<?php echo $userinfo->getDisplayname(); ?>" readonly="true">
                </div>
                <div class="form-group">
                  <label for="inputemail">Email address</label>
                  <input type="email" class="form-control" name="inputemail" id="inputemail" value="<?php echo $userinfo->getEmail(); ?>" readonly="true">
                </div>
                <div class="form-group">
                  <label for="inputphone">Phone</label>
                  <input type="text" class="form-control" name="inputphone" id="inputphone" value="<?php echo $userinfo->getPhonenum(); ?>" readonly="true">
                </div>
                <div class="form-group">
                  <label for="inputmessage">Message</label>
                  <textarea class="form-control" id="inputmessage" name="inputmessage" placeholder="Your Message" rows="8"></textarea>
                </div>
                <button type="submit" class="btn btn-success">Submit Request</button>
            </form>
            </div>
            <p>&nbsp;</p>
          </div>
        </div>
    </div>
</div>
