<div class="content-header">
    <div class="header-section">
        <h1>
            <strong><?= $pageTitle ?></strong> 
        </h1>
    </div>
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="block">
            <div class="block-title">
                <h2><i class="fa fa-file-o"></i><strong> <?= $pageTitle ?></strong><h2>
            </div>
            <div class="block-body">
            <h3>Terms & Conditions</h3>
            <p>Bright Life Foundation supports the students, the future of tomorrow's growth with all humility and passion. Our NGO distributed scholarships class 8th to 12th from all India schools. This Competition also offers the valuable opportunity to the students to compete with thousands of other students and to judge their performance.</p>

            <h4>Who can Participate??</h4>
            <p>Any 8th to graduate first year student (Full Time/Part Time/Executive/Distance) in the year 2016.</p>

            <h4>Other Terms & Conditions !!!</h4>
            <ul>
            <li>This Competition is open only for students 8th to graduate first year student in the year 2016</li>
            <li>Competition will be conducted via www.online-exam.in, conducted online, students can participate only once for this Online Exam.</li>
            <li>Final Result will be based on the total marks obtained by the students in Online Quiz</li>
            <li>Scholarship will be paid directly to the Student through Demand Draft/Online Payment.</li>
            <li>Scholarship & other rewards are non-transferrable & non-redeemable</li>
            <li>Bright Life Foundation reserves the rights to change any terms of the eScholarship Competition with or without prior notice to the student/s</li>
            <li>In case of any dispute; decision by Bright Life Foundation, its authorized representatives, Test Invigilator will be final & binding to the students.</li>
            <li>Students are advised to regularly visit the website (www.blfngoindia.org) for new updates about the eScholarship</li>
            <li>Any taxes if applicable on the cash scholarship will be borne by winners</li>
            </ul>
            </div>
        </div>
    </div>
</div>