<div class="content-header">
    <div class="header-section">
    	<div class="pull-right">My Referral Code : <span class="bg-primary"><strong>&nbsp;&nbsp;<?= $studinfo->strefcode; ?>&nbsp;&nbsp;</strong></span></div>
        <h1>
            <strong><?= $pageTitle ?></strong> 
        </h1>
    </div>
</div>

<div class="row" data-ng-app>
    <div class="col-lg-12">
        <div class="block">
            <div class="block-title">
            	<div class="pull-right"><a href="/streferral/referral-dashboard" class="btn btn-xs btn-warning">Referral Dashboard</a>
            	&nbsp;&nbsp;&nbsp;
            	<a href="/streferral/referral-email-form" class="pull-right btn btn-xs btn-info">Refer by Email</a></div>
                <h2><i class="fa fa-file-o"></i> Referral SMS Form<h2>
            </div>
            <div class="block-body">
                <?php if(!empty($sucmsg)) { ?>
                    <div class="alert alert-success text-center"><h4><?= $sucmsg; ?></h4></div>
                <?php } ?>
            	<form class="form" action="#" method="post">

            		<div class="form-group">
            			<input type="text" name="rfrname" class="form-control" placeholder="Name" data-ng-model="name" required/>
            		</div>
            		<div class="form-group">
            			<input type="text" name="rfrphone" class="form-control" placeholder="Phone Number" maxlength="10" required/>
            		</div>
            		<div class="form-group">
	            		<h4>Dear {{name}},</h4>
	            		<p><strong><?= $studinfo->getFirstName(); ?></strong> referred you for eScholarship program. Visit www.blfngoindia.org to register with Referral Code <strong><?= $studinfo->getStrefcode(); ?></strong>
	            		</p>
            		</div>
            		<div class="form-group">
            			<input type="submit" name="rfemsub" class="btn btn-primary" value="Send" />
            		</div>


            	</form>
            </div>
        </div>
    </div>
</div>